export const SENIORITY_TIERS = [
  { rank: 1, label: "Individual Contributor" },
  { rank: 2, label: "Senior Individual Contributor" },
  { rank: 3, label: "Manager" },
  { rank: 4, label: "Senior Manager" },
  { rank: 5, label: "Director" },
  { rank: 6, label: "VP" },
  { rank: 7, label: "SVP / EVP" },
  { rank: 8, label: "C-Suite / President" },
] as const;

export const ALLOWED_FILTER_FIELDS = [
  "snapshot.fullName",
  "snapshot.firstName",
  "snapshot.lastName",
  "snapshot.currentTitle",
  "snapshot.currentCompany",
  "snapshot.currentCompanyId",
  "snapshot.industry",
  "snapshot.location",
  "snapshot.city",
  "snapshot.state",
  "snapshot.stateCode",
  "snapshot.country",
  "snapshot.countryCode",
  "snapshot.connections",
  "snapshot.email",
  "snapshot.phone",
  "snapshot.degree",
  "snapshot.skills",
  "snapshot.roles.title",
  "snapshot.roles.companyName",
  "snapshot.roles.isCurrent",
  "snapshot.education.school",
  "snapshot.education.degree",
  "snapshot.education.field",
  "derived.leadScore",
  "derived.segment",
  "meta.lastObservedAt",
  "createdAt",
] as const;

export const ALLOWED_SORT_FIELDS = [
  "snapshot.fullName",
  "snapshot.currentTitle",
  "snapshot.currentCompany",
  "snapshot.connections",
  "snapshot.city",
  "snapshot.state",
  "snapshot.country",
  "meta.lastObservedAt",
  "meta.observationsCount",
  "createdAt",
  "updatedAt",
  "derived.leadScore",
] as const;

export const FILTER_OPERATORS = [
  { value: "$eq", label: "equals" },
  { value: "$ne", label: "not equals" },
  { value: "$gt", label: "greater than" },
  { value: "$gte", label: "greater than or equal" },
  { value: "$lt", label: "less than" },
  { value: "$lte", label: "less than or equal" },
  { value: "$in", label: "in (comma-separated)" },
  { value: "$nin", label: "not in (comma-separated)" },
  { value: "$regex", label: "matches regex" },
  { value: "$exists", label: "exists" },
] as const;

export const SIGNAL_TYPES = [
  "new_role",
  "promotion",
  "lateral_move",
  "new_decision_maker",
] as const;

export const FIELD_LABELS: Record<string, string> = {
  "snapshot.fullName": "Full Name",
  "snapshot.firstName": "First Name",
  "snapshot.lastName": "Last Name",
  "snapshot.currentTitle": "Title",
  "snapshot.currentCompany": "Company",
  "snapshot.currentCompanyId": "Company ID",
  "snapshot.industry": "Industry",
  "snapshot.location": "Location",
  "snapshot.city": "City",
  "snapshot.state": "State",
  "snapshot.stateCode": "State Code",
  "snapshot.country": "Country",
  "snapshot.countryCode": "Country Code",
  "snapshot.connections": "Connections",
  "snapshot.email": "Email",
  "snapshot.phone": "Phone",
  "snapshot.degree": "Degree",
  "snapshot.skills": "Skills",
  "snapshot.roles.title": "Role Title",
  "snapshot.roles.companyName": "Role Company",
  "snapshot.roles.isCurrent": "Is Current Role",
  "snapshot.education.school": "School",
  "snapshot.education.degree": "Education Degree",
  "snapshot.education.field": "Education Field",
  "derived.leadScore": "Lead Score",
  "derived.segment": "Segment",
  "meta.lastObservedAt": "Last Observed",
  createdAt: "Created",
  updatedAt: "Updated",
  "meta.observationsCount": "Observations",
};
