/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as SignalsIndexRouteImport } from "./routes/signals/index"
import { Route as QueryIndexRouteImport } from "./routes/query/index"
import { Route as PeopleIndexRouteImport } from "./routes/people/index"
import { Route as InsightsIndexRouteImport } from "./routes/insights/index"
import { Route as HealthIndexRouteImport } from "./routes/health/index"
import { Route as PeopleIdRouteImport } from "./routes/people/$id"
import { Route as CompaniesIdRouteImport } from "./routes/companies/$id"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsIndexRoute = SignalsIndexRouteImport.update({
  id: "/signals/",
  path: "/signals/",
  getParentRoute: () => rootRouteImport,
} as any)
const QueryIndexRoute = QueryIndexRouteImport.update({
  id: "/query/",
  path: "/query/",
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleIndexRoute = PeopleIndexRouteImport.update({
  id: "/people/",
  path: "/people/",
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: "/insights/",
  path: "/insights/",
  getParentRoute: () => rootRouteImport,
} as any)
const HealthIndexRoute = HealthIndexRouteImport.update({
  id: "/health/",
  path: "/health/",
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleIdRoute = PeopleIdRouteImport.update({
  id: "/people/$id",
  path: "/people/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIdRoute = CompaniesIdRouteImport.update({
  id: "/companies/$id",
  path: "/companies/$id",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/companies/$id": typeof CompaniesIdRoute
  "/people/$id": typeof PeopleIdRoute
  "/health/": typeof HealthIndexRoute
  "/insights/": typeof InsightsIndexRoute
  "/people/": typeof PeopleIndexRoute
  "/query/": typeof QueryIndexRoute
  "/signals/": typeof SignalsIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/companies/$id": typeof CompaniesIdRoute
  "/people/$id": typeof PeopleIdRoute
  "/health": typeof HealthIndexRoute
  "/insights": typeof InsightsIndexRoute
  "/people": typeof PeopleIndexRoute
  "/query": typeof QueryIndexRoute
  "/signals": typeof SignalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/companies/$id": typeof CompaniesIdRoute
  "/people/$id": typeof PeopleIdRoute
  "/health/": typeof HealthIndexRoute
  "/insights/": typeof InsightsIndexRoute
  "/people/": typeof PeopleIndexRoute
  "/query/": typeof QueryIndexRoute
  "/signals/": typeof SignalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/companies/$id"
    | "/people/$id"
    | "/health/"
    | "/insights/"
    | "/people/"
    | "/query/"
    | "/signals/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/companies/$id"
    | "/people/$id"
    | "/health"
    | "/insights"
    | "/people"
    | "/query"
    | "/signals"
  id:
    | "__root__"
    | "/"
    | "/companies/$id"
    | "/people/$id"
    | "/health/"
    | "/insights/"
    | "/people/"
    | "/query/"
    | "/signals/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompaniesIdRoute: typeof CompaniesIdRoute
  PeopleIdRoute: typeof PeopleIdRoute
  HealthIndexRoute: typeof HealthIndexRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
  PeopleIndexRoute: typeof PeopleIndexRoute
  QueryIndexRoute: typeof QueryIndexRoute
  SignalsIndexRoute: typeof SignalsIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/signals/": {
      id: "/signals/"
      path: "/signals"
      fullPath: "/signals/"
      preLoaderRoute: typeof SignalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/query/": {
      id: "/query/"
      path: "/query"
      fullPath: "/query/"
      preLoaderRoute: typeof QueryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/people/": {
      id: "/people/"
      path: "/people"
      fullPath: "/people/"
      preLoaderRoute: typeof PeopleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/insights/": {
      id: "/insights/"
      path: "/insights"
      fullPath: "/insights/"
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/health/": {
      id: "/health/"
      path: "/health"
      fullPath: "/health/"
      preLoaderRoute: typeof HealthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/people/$id": {
      id: "/people/$id"
      path: "/people/$id"
      fullPath: "/people/$id"
      preLoaderRoute: typeof PeopleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/companies/$id": {
      id: "/companies/$id"
      path: "/companies/$id"
      fullPath: "/companies/$id"
      preLoaderRoute: typeof CompaniesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompaniesIdRoute: CompaniesIdRoute,
  PeopleIdRoute: PeopleIdRoute,
  HealthIndexRoute: HealthIndexRoute,
  InsightsIndexRoute: InsightsIndexRoute,
  PeopleIndexRoute: PeopleIndexRoute,
  QueryIndexRoute: QueryIndexRoute,
  SignalsIndexRoute: SignalsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
