services:
  - type: web
    name: duxsoup-etl
    env: node
    plan: free
    buildCommand: npm install && cd client && npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: duxsoup-etl-db
          property: connectionString
    healthCheckPath: /health